version: "3.8"

services:
  mysql:
    image: docker.io/library/mysql:8
    restart: always
    env_file:
      - ./SpringBoot/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: TradeAnalytics
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:Z
    networks:
      - trademargin-net

  backend:
    image: ghcr.io/s4nxez/trade-margin-analytics-back:latest
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./SpringBoot/.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/TradeAnalytics
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: spring
    networks:
      - trademargin-net

  frontend:
    image: ghcr.io/s4nxez/trade-margin-analytics-front:latest
    restart: always
    networks:
      - trademargin-net

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - trademargin-net

volumes:
  mysql_data:
  caddy_data:
  caddy_config:

networks:
  trademargin-net:
    external: false
